### ISSUE TITLE
There are no valid initial states simulation error

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/local-pathfinding#135]
[Error Running Simulation.txt](https://github.com/UBCSailbot/local-pathfinding/files/5322169/Error.Running.Simulation.txt)

**Comment by tylerlum** [comment]
@patrick-5546 here are the places I believe the problem comes from. When we run `createNewLocalPath(state)`, we need to be sure that the start position is valid. If it is invalid, it will cause this issue. I think this is the way we currently check start position validity.

https://github.com/UBCSailbot/local-pathfinding/blob/master/python/main_loop.py#L83
https://github.com/UBCSailbot/local-pathfinding/blob/master/python/main_loop.py#L145
https://github.com/UBCSailbot/local-pathfinding/blob/master/python/main_loop.py#L171

**Comment by tylerlum** [comment]
Consider adding regression tests to ensure this does not come up again.

**Comment by tylerlum** [comment]
Resolved in #142
