### ISSUE TITLE
Handle boat drift (likely from current)

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#170]
The boat may drift left or right from current. However, our system has two aspects that need changes:

1. Model this movement (in MOCK_controller_and_boat.py). Something like use_current:=true or current_speed=1 current_direction=90 (DONE)

2. Change how we "reach" a local waypoint, as drift makes it go "upwind" when it gets close. Maybe move the "line" back by 1/8th of waypoint distance. (DONE)

3. Change how we calculate measured/global wind. Right now, assumes all boat speed in the heading direction

4. Talk to Simon about potentially measuring current, else just need to do track made good/ true heading calculation. (probably too hard to do)

5. Test out the system in different current scenarios and find solutions if there are problems

![image](https://user-images.githubusercontent.com/26510814/101263115-c67f8500-36f7-11eb-9dbd-3530a0508c78.png)

Potentially use these numbers to calculate current, but might be inaccurate. Currently code assumes track made good == heading

**Comment by tylerlum** [comment]
Added in current in #174. May still need to make changes to handle current.

**Comment by tylerlum** [comment]
Now that we can turn on and off current, test out the boat in different current speeds and directions.

Try out and document the following:
* Low speed, middle speed, high speed (boat speed is about 14.4 kmph, so try 1 kmph, 5kmph, 12kmph). (maybe do research to see real expected values
* Try out 45, 0, 90 degrees

**Comment by patrick-5546** [comment]
Carried out tests as outlined in the previous comment. Here are some of my observations:
- Sometimes the distance between waypoints becomes really small.
![waypoints close](https://user-images.githubusercontent.com/65756895/107734601-a5688100-6cb2-11eb-9ea7-429c91b1370f.png)
- The boat will stall for a long time (30 seconds - 1 minute) when the path is heading upwind before changing paths.
![stalled, directly upwind, took a while till made a path straight](https://user-images.githubusercontent.com/65756895/107734669-d3e65c00-6cb2-11eb-9252-c865a78e7365.png)
- Sometimes the current can cause the boat to tilt, which in some cases causes the waypoint reached line to move as well.
![perpen, uturn](https://user-images.githubusercontent.com/65756895/107734732-f37d8480-6cb2-11eb-87e1-f1e8a73f63d2.png)
![parallel, uturn](https://user-images.githubusercontent.com/65756895/107734740-f8dacf00-6cb2-11eb-8610-534d6c00f8ce.png)

I can present my findings in more detail during one of the meetings.

**Comment by patrick-5546** [comment]
### Launch Arguments
```
roslaunch local_pathfinding all.launch initial_speedup:=400 random_seed:=100 ocean_current_speed:=10 ocean_current_direction:=315
```

### Observations
1. The triangle tip passes the waypoint reached line. However, I am not sure this is an issue, as eventually it pauses somewhere within the triangle body. The first screenshot is where the boat paused.
2. Occasionally with the launch arguments outlined above. The boat will pause and resume with a different waypoint reached line towards the same local waypoint. This new waypoint reached line seems to be perpendicular to the line connecting the boat and waypoint. Since it is upwind, the boat sometimes takes quite a while before moving on to the next local waypoint.

#### Location of first pause
![Screenshot from 2021-02-18 20-45-20](https://user-images.githubusercontent.com/65756895/108459246-2384d480-722b-11eb-9774-c98e755e93a7.png)
#### Different waypoint reached line for the same waypoint
![Screenshot from 2021-02-18 20-45-24](https://user-images.githubusercontent.com/65756895/108459262-297ab580-722b-11eb-8496-084c2c3d67fb.png)
There was a second adjustment of the waypoint reached line when the boat rotated a bit, but I was not fast enough to screenshot it.

**Comment by tylerlum** [comment]
Thanks so much for finding and documenting this. I found this issue, but was unable to reproduce it. Your code had it able to reproduce quite easily. Need to investigate this. Definitely something not working right

**Comment by tylerlum** [comment]
Great progress on this issue. Most have been resolved, but will look into the other heading vs. track made good in another issue.
