### ISSUE TITLE
Debug and resolve issue when sailbot tries to go to very far away global waypoint

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#190]
![image](https://user-images.githubusercontent.com/26510814/111043740-06da5780-83f9-11eb-9908-eb43e22cba8c.png)

Sometimes the sailbot tries to go to a very far away waypoint. Should be going to waypoint ~30km away, but starts going 100km away or more. Potential reason:

From main_loop.py, we tell the sailbot to go to the next global waypoint if we reach the waypoint or if the global waypoint is invalid. Likely not from reaching next global waypoint, as this seems to be implemented properly. Issue is when there is a boat on the global waypoint, making it invalid. Then the system can't do pathfinding to that point, so we skip that waypoint. Likely find another solution like move the waypoint slightly left or right, or just ignore the boat unless 1 waypoint away (or n waypoints away).
![image](https://user-images.githubusercontent.com/26510814/111043762-28d3da00-83f9-11eb-9ee5-eeae14169604.png)

**Comment by tylerlum** [comment]
Can recreate this issue by running roslaunch local_pathfinding all.launch, then looking at the latlon of the star, then put that into 

```
rostopic pub /new_boats sailbot_msg/AISShip "{ID: 0, lat: 48.285, lon: -125.021, headingDegrees: 90.0, speedKmph: 1.0}"
```

Slighlty adjust to get boat on the star

**Comment by patrick-5546** [comment]
My idea is to move the global waypoint closer to sailbot on the line connecting them. The reason I think that the new global waypoint should be closer is so that sailbot can generate a path around the obstacle at the old global waypoint when it is closer to that obstacle.

My implementation would involve creating a new method in `handleInvalidState.py` that moves `state.globalWaypoint` in `n` km increments while `checkGoalValidity(state)` is false. To do this, I would need sailbot's current position, and the ability to modify `state.globalWaypoint`.

Is there a way to get sailbot's current position from `state`? Would reassigning `state.globalWaypoint` mess anything up?

**Comment by tylerlum** [comment]
![image](https://user-images.githubusercontent.com/26510814/113487799-ebe68a80-946e-11eb-9682-754e8bb8225b.png)

Seems to be acting up a bit, looking into it

**Comment by tylerlum** [comment]
Additional bug found: localPath.lastWaypointReached() is returning true when it should return false. For example, if the boat is very far away, but the lastWaypointReached line is in the wrong direction, then it will think localPath.lastWaypointReached() is true.
![image](https://user-images.githubusercontent.com/26510814/113488828-5bf80f00-9475-11eb-95cf-f130d1d68b38.png)

In case 1, boat upper right taking the green path that has a kink. This thinks localPath.lastWaypointReached() is true. It should also check first if lastWaypoint = nextWaypoint.

**Comment by tylerlum** [comment]
# assumes there are at least 2 elements in self._latlons
    def lastWaypointReached(self, positionLatlon):
        if self._nextWaypointIndex == len(self._latlons) - 1:
            return self.nextWaypointReached(self, positionLatlon)
        return False

Proposed solution
